### ISSUE TITLE
use long keys for the enckeys property

### ISSUE THREAD

**Issue by michael-kerscher** [adulau/global-irt#6]
the enckeys property only returns the encryption keys in short id format, e.g. 0xBADCOFFE
As collisions in the short id space are nowadays very easily done the preferred key format should be long id e.g. 0xDEADBEEFBADCOFFE

**Comment by shrekts** [comment]
Please move it to repo https://github.com/FIRSTdotorg/global-irt

**Comment by michael-kerscher** [comment]
moved
