### ISSUE TITLE
the email property should be a list of emails

### ISSUE THREAD

**Issue by michael-kerscher** [adulau/global-irt#7]
Other fields like phone-numbers and enckeys already are lists. Making the email field an "emails" list field would be a good idea as there might be more than one email per organisation (and therefore a reason for multiple enckeys). You could store multiple emails comma separated but then a client has to parse this list if he wants to know which encryption key is used for a specific email address, etc.

**Comment by shrekts** [comment]
Please move it to repo https://github.com/FIRSTdotorg/global-irt

**Comment by michael-kerscher** [comment]
moved
