### ISSUE TITLE
operating-hours property definition misses timezones and is different in api.md and ExistingFormatReview in the wiki

### ISSUE THREAD

**Issue by michael-kerscher** [adulau/global-irt#8]
The wiki deviates from the definition found in api.md.
In the wiki operating-hours is defined as as a dict of dicts (day -> {from, to}) and api.md says it is an string type. At the moment the api,first.org is using untyped string type. For better support in tools to show availability it would be good if operating hours are saved in a structured way.

Also including timezone information to these operating hours to be useful.

**Comment by shrekts** [comment]
Please move it to repo https://github.com/FIRSTdotorg/global-irt

**Comment by michael-kerscher** [comment]
moved
